config/routes.rb
Rails.application.routes.draw do
  resources :bans

  root :to => 'posts#index'
  match 'users' => 'posts#index', :via => :delete
  get 'formatting_help' => 'pages#formatting_help'
  get 'data_collection' => 'pages#data_collection'
  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  resources :users, :only => [:show]

  resources :posts do
    collection do
      get 'search'
      get 'latest'
      post 'preview'
      put 'preview'
      patch 'preview'
    end
  end

  match 'posts/tagged/:tag_id' => 'posts#tagged', :via => :get, :as => :tagged
  match 'posts/scrape/:year/:month' => 'posts#scrape', :via => :get, :as => :scrape
  match 'posts/:post_id/watch' => 'watches#create', :via => :post
  match 'posts/:post_id/watch' => 'watches#destroy', :via => :delete

end

app/models/ban.rb
class Ban < ApplicationRecord
  belongs_to :user, :optional => true

  validates :length, :reason, :presence => true

  def self.find_ban(conditions)
    ban = self.where(conditions).first
    # < is "is earlier in time than"
    if ban && ban.length != 0 && (ban.created_at + ban.length.seconds) < Time.now
      ban.destroy
      ban = nil
    end
    ban
  end
end

app/controllers/bans_controller.rb
# frozen_string_literal: true
class BansController < ApplicationController
  skip_before_action :ip_ban, :check_ban, :only => [ :show ]
  before_action :authenticate_user!, :except => [ :show ]
  before_action :must_be_moderator!, :except => [ :show, :index ]

  # GET /bans
  # GET /bans.json
  def index
    @bans = Ban.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bans }
    end
  end

  # GET /bans/1
  # GET /bans/1.json
  def show
    @ban = Ban.find(params[:id])

    respond_to do |format|
      format.html { render :show, :status => :forbidden } # show.html.erb
      format.json { render json: @ban }
    end
  end

  # GET /bans/new
  # GET /bans/new.json
  def new
    @ban = Ban.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ban }
    end
  end

  # GET /bans/1/edit
  def edit
    @ban = Ban.find(params[:id])
  end

  # POST /bans
  # POST /bans.json
  def create
    @ban = Ban.new(ban_params)

    respond_to do |format|
      if @ban.save
        format.html { redirect_to root_path, notice: 'Ban was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @ban.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bans/1
  # PUT /bans/1.json
  def update
    @ban = Ban.find(params[:id])

    respond_to do |format|
      if @ban.update(ban_params)
        format.html { redirect_to root_path, notice: 'Ban was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ban.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bans/1
  # DELETE /bans/1.json
  def destroy
    @ban = Ban.find(params[:id])
    @ban.destroy

    respond_to do |format|
      format.html { redirect_to bans_url }
      format.json { head :no_content }
    end
  end

  private
  def ban_params
    params.require(:ban).permit(:email, :ip, :user_id, :length, :reason)
  end
end

app/helpers/bans_helper.rb
module BansHelper
end

app/views/bans/_form.html.erb
<%= simple_form_for(@ban) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :length, :hint => 'In seconds. 0 is an infinite ban. Be careful with those.' %>
    <%= f.input :reason %>
    <%= f.association :user %>
    <%= f.input :ip %>
    <%= f.input :email %>
  </div>

  <div>
    <%= f.button :submit, :class => 'btn btn-danger', :role => 'button' %>
  </div>
<% end %>

app/views/bans/edit.html.erb
<% title("Editing ban") %>
<h1><%= yield :title %></h1>

<%= link_to 'Never Mind', bans_path, :class => 'btn btn-success', :role => 'button' %>

<%= render 'form' %>

<%= link_to 'Never Mind', bans_path, :class => 'btn btn-success', :role => 'button' %>

app/views/bans/index.html.erb
<% title("List of bans") %>
<h1><%= yield :title %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Ip</th>
      <th>Email</th>
      <th>Length (seconds)</th>
      <th>Until</th>
      <th>Time remaining</th>
      <th>Reason</th>
      <% if current_user.moderator? %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @bans.each do |ban| %>
    <tr>
      <td><%= ban.user && ban.user.name %></td>
      <td><%= ban.ip %></td>
      <td><%= ban.email %></td>
      <td><%= ban.length %></td>
      <td>
        <% if ban.length == 0 %>
          Eternity
        <% else %>
          <%= ban.created_at + ban.length.seconds %>,
        <% end %>
      </td>
      <td>
        <% if ban.length == 0 %>
          All time
        <% else %>
          <%= distance_of_time_in_words(Time.now, ban.created_at + ban.length.seconds) %>.
        <% end %>
      <td><%= ban.reason %></td>
      <% if current_user.moderator? %>
        <td><%= link_to 'Edit', edit_ban_path(ban) %></td>
        <td><%= link_to 'Revert', ban, method: :delete %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br />
<% if current_user.moderator? %>
<%= link_to 'New Ban', new_ban_path, :class => 'btn btn-danger', :role => 'button' %>
<% end %>

app/views/bans/new.html.erb
<% title("New ban") %>
<h1><%= yield :title %></h1>
<p class="lead">This form should be used only for spammers and the like
  or with community consensus.
</p>

<%= link_to 'Never Mind', bans_path, :class => 'btn btn-success', :role => "button" %>

<%= render 'form' %>

<%= link_to 'Never Mind', bans_path, :class => 'btn btn-success', :role => "button" %>

app/views/bans/show.html.erb
<% title("403 - You\'re Banned!") %>
<h1><%= yield :title %></h1>
<p>
<% if @ban.user_id != nil %>
The user <%= @ban.user.name %> is banned.
<% end %>
<% if @ban.ip != nil && @ban.ip != "" %>
The IP address <%= @ban.ip %> is banned.
<% end %>
The reason for this ban is: "<%= @ban.reason %>".
<% if @ban.length == 0 %>
This ban is permanent.
<% else %>
This ban will last until <%= @ban.created_at + @ban.length.seconds %>,
that is, for
<%= distance_of_time_in_words(Time.now, @ban.created_at + @ban.length.seconds) %> more.
<% end %>
</p>
<p>
If you believe you've been banned in error, please
contact the Board admin at <%= mail_to(SITE_CONFIG[:admin_contact]) %>
</p>