config/routes.rb
Rails.application.routes.draw do
  resources :bans

  root :to => 'posts#index'
  match 'users' => 'posts#index', :via => :delete
  get 'formatting_help' => 'pages#formatting_help'
  get 'data_collection' => 'pages#data_collection'
  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  resources :users, :only => [:show]

  resources :posts do
    collection do
      get 'search'
      get 'latest'
      post 'preview'
      put 'preview'
      patch 'preview'
    end
  end

  match 'posts/tagged/:tag_id' => 'posts#tagged', :via => :get, :as => :tagged
  match 'posts/scrape/:year/:month' => 'posts#scrape', :via => :get, :as => :scrape
  match 'posts/:post_id/watch' => 'watches#create', :via => :post
  match 'posts/:post_id/watch' => 'watches#destroy', :via => :delete

end

app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord
  ## NOTE: next_version should be current_version,
  ## but renaming it to reflect the actual semantics of the code seems tricky
  has_ancestry orphan_strategy: :adopt
  lazy_load :body

  attr_readonly :parent_id
  before_create :set_sort_timestamp

  before_destroy :drop_from_edit_chain
  before_destroy :migrate_next_version

  after_save :invalidate_thread_cache

  belongs_to :previous_version, :class_name => 'Post', :foreign_key => 'previous_version_id', :optional => true
  belongs_to :next_version, :class_name => 'Post', :foreign_key => 'next_version_id', :optional => true
  has_and_belongs_to_many :tags
  belongs_to :user
  has_and_belongs_to_many :watchers, -> { distinct }, :class_name => 'User'

  validate :no_memory_hole, :on => :update
  validate :no_locked_reply, :on => :create
  validate :flood_prevention, :on => :create
  validates :subject, :author, :user_id, :presence => true
  validates_length_of :subject, :minimum => 1, :maximum => 105
  validates_length_of :author, :minimum => 1, :maximum => 80

  attr_accessor :watch_add
  attr_accessor :override_sort_timestamp

  attr_accessor :being_cloned

  self.per_page = 25

  def self.searchable_language
    'english'
  end
  def self.searchable_columns
    [:subject, :author, :body]
  end

  def clone_before_edit
    clone = Post.new
    load_body = self.body # Skip lazy_columns
    attrs = self.attributes
    attrs.delete("id")
    clone.update(attrs)
    clone.being_cloned = true
    # Note, all pasts of a post have a next_version of the most recent version.
    # This is now a feature.
    clone.next_version = self
    clone.sort_timestamp = self.sort_timestamp
    clone.save!
    clone.being_cloned = false
    clone
  end

  def close_edit_cycle(clone)
    self.previous_version = clone
    self.save!
  end

  DAY = 24.hours

  def recent?
    Time.now - self.created_at < DAY
  end

  def new_reply?
    (Time.now - self.created_at < DAY) && (Time.now - self.root.created_at > DAY) && !self.is_root?
  end

  def seeing_activity?
    (Time.now - self.updated_at) < DAY
  end

  def reSorted?
    (self.sort_timestamp - self.created_at).abs > 60
  end

  private

  def no_memory_hole
    self.next_version
    if self.next_version && !self.being_cloned
      errors.add(:base, "You aren\'t allowed to edit anything other than the current version of a post. What is this, 1984?")
    end
  end

  def no_locked_reply
    if self.locked || self.ancestors.where(:locked => true).exists?
      errors.add(:base, "You aren't allowed to reply to locked threads.")
    end
  end

  def flood_prevention
    if !Rails.env.test? && !self.being_cloned &&
       Post.where(:user_id => self.user_id, :created_at => 10.second.ago..Time.now).exists?
      errors.add(:base, "You can only create one post every 10 seconds to prevent spam")
    end
  end

  def set_sort_timestamp
    if (not self.sort_timestamp) || (self.override_sort_timestamp != "1")
      self.sort_timestamp = Time.now
    end
  end

  def drop_from_edit_chain
    Post.where(:previous_version => self).each do |p|
      p.previous_version = self.previous_version
      p.being_cloned = true
      p.save!
      p.being_cloned = false
    end
  end

  def migrate_next_version
    Post.where(:next_version => self).each do |p|
      if self.previous_version == p
        p.next_version = nil
        p.save!
      else
        p.next_version = self.previous_version
        p.being_cloned = true
        p.save!
        p.being_cloned = false
      end
    end
  end

  def invalidate_thread_cache
    self.root.touch
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true
class PostsController < ApplicationController
  before_action :clear_return_url
  skip_before_action :ip_ban, :check_ban,
                     :except => [:new, :create, :update, :edit, :preview, :destroy]
  before_action :authenticate_user_board!,
                :only => [:new, :create, :update, :edit, :preview, :destroy]
  before_action :must_be_moderator!, :only => [:destroy]
  helper_method :allowed_to_edit?

  # GET /posts/search
  # GET /posts/search.json
  def search
    @query = params[:query] || ""
    @posts = Post.order("sort_timestamp DESC")
               .web_search(@query).paginate(:page => params[:page])
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    if params[:sort_mode]
      cookies.delete :sort_mode
      cookies[:sort_mode] = {:value => params[:sort_mode], :expires => 20.years.from_now}
    end
    cookies.delete :last_subforum

    @posts = Post.where(:ancestry => nil, :next_version_id => nil)
                 .paginate(:page => params[:page]).order("sort_timestamp DESC")

    @tagged_posts = Hash.new do |hash, key|
      hash[key] = []
    end
    if cookies[:sort_mode] == "tag" || cookies[:sort_mode] == "subforum"
      @posts.each do |thread|
        unless thread.tags.any?
          @tagged_posts[false] << thread #This takes care of "no tags at all"
        end
        tags = {}
        thread.subtree.each do |post|
          if post.tags.any?
            post.tags.each do |tag|
              tags[tag] = true
            end
          end
        end
        if tags.length > 0
          tags.each do |tag, _|
            @tagged_posts[tag] << thread
          end
        end
      end
    else
      @tagged_posts[false] = @posts
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/latest
  # GET /posts/latest.json
  # GET /posts/latest.atom
  def latest
    @posts = Post.where(:next_version_id => nil)
      .paginate(:page => params[:page]).order("sort_timestamp DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /posts/tagged/1
  # GET /posts/tagged/1.json
  def tagged
    cookies[:last_subforum] = {:value => params[:tag_id], :expires => 3.months.from_now}

    if params[:tag_id] == "nothing"
      @tag = false
      @raw_posts = Post.joins("LEFT JOIN posts_tags pt ON pt.post_id = posts.id")
                       .where("pt.tag_id" => nil, "posts.next_version_id" => nil, "posts.ancestry" => nil)
                       .paginate(:page => params[:page]).order("posts.sort_timestamp DESC")
      @posts = @raw_posts.map(&:root)
      @posts.uniq!
    else
      @tag = Tag.find(params[:tag_id])
      @raw_posts = @tag.posts.where(:next_version_id => nil)
                       .paginate(:page => params[:page]).order("sort_timestamp DESC")
      @posts = @raw_posts.map(&:root)
      @posts.uniq!
    end

    respond_to do |format|
      format.html # tagged.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/scrape/2016/01{a,b}
  # GET /posts/scrape/2016/01{a,b}.json
  # GET /posts/scrape/2016/01?user_id=1
  # ...
  def scrape
    if cookies["foo"] != "bar"
      return head :forbidden
    end
    @month_num = params[:month][0..-2].to_i(10)
    @month_side = params[:month][-1]
    @year = params[:year].to_i(10)
    date = DateTime.new(@year, @month_num)
    one_third = date.beginning_of_month + 10.days
    two_thirds = date.beginning_of_month + 20.days
    range =
        if @month_side == 'a'
          date.beginning_of_month..one_third
        elsif @month_side == 'b'
          one_third..two_thirds
        elsif @month_side == 'c'
          two_thirds..date.end_of_month
        else
          date.beginning_of_month..date.end_of_month
        end
    conditions = {:ancestry => nil, :next_version_id => nil,
                  :sort_timestamp => range}
    if params[:user_id]
      conditions[:user_id] = params[:user_id].to_i(10)
    end
    @posts = Post.where(conditions).order("sort_timestamp ASC")

    status = @posts.empty? ? :not_found : :ok
    respond_to do |format|
      format.html { render status: status } # scrape.html.erb
      format.json { render json: @posts, status: status }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { @post.body; render json: @post }
    end
  end

  # POST /posts/preview
  # PUT /posts/preview
  # PATCH /posts/preview
  def preview
    @post = Post.new(post_params)
    @post.user = current_user
    add_nm(@post)

    respond_to do |format|
      format.html { render :partial => 'post', :object => @post, :locals => {:hide_status_info => true} }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new(:parent_id => params[:parent_id], :author => current_user.name,
                     :tag_ids => [params[:tag_id]])
    locked_post_reply = false
    if params[:parent_id]
      parent_post = Post.find(params[:parent_id])
      locked_post_reply = (parent_post.locked) || (parent_post.ancestors.where(:locked => true).any?)
    end

    respond_to do |format|
      format.html { flash[:warning] = "You're trying to reply to a locked post, which is not allowed" if locked_post_reply } # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    unless allowed_to_edit? @post, current_user
      redirect_to posts_url, :flash => {:error => "You can't edit other people's posts."}
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    adding_watch = (@post.watch_add == "1")
    @post.user = current_user
    add_nm(@post)

    respond_to do |format|
      if @post.save
        notify_watchers(@post)
        if adding_watch
          @post.watchers << current_user
        end
        # Restore to auto-subscribe people to things they post
        # unless @post.ancestors.all.any? do |post|
        #     post.watchers.exists?(current_user.id)
        #   end
        #   @post.watchers = [current_user]
        # end
        format.html { flash[:success] = ["Post was successfully created."]
        redirect_to @post }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      unless allowed_to_edit? @post, current_user
        redirect_to posts_url, :flash => {:error => "You can't edit other people's posts. Also, why are you bypassing access controls?"}
        logger.error("#{current_user.name} (#{current_user.id}) is trying to PUT #{@post.author}'s post (#{post.id}). CRACKER!")
      end
      @clone = @post.clone_before_edit
      @post.user = current_user
      if @post.update(post_params)
        @post.close_edit_cycle @clone
        format.html { flash[:success] = ["Post was successfully updated."]
          redirect_to @post }
        format.json { head :no_content }
      else
        @clone.destroy
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    respond_to do |format|
      unless user_signed_in? && current_user.moderator?
        redirect_to posts_url, :flash => {:error => "You can't delete posts unless you're a moderator"}
        logger.error("#{current_user.name} (#{current_user.id}) is trying to DELETE #{@post.author}'s post (#{post.id}). CRACKER!")
      end

      if @post.destroy
        format.html { flash[:success] = ["Post successfully deleted."]
        redirect_to(root_path) }
        format.json { head :no_content }
      else
        format.html { render action: "show", flash: {error: "Failed to delete post"} }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def allowed_to_edit?(post, user)
    return false unless user
    status = post.user_id == user.id || user.moderator?
    if !status && (post.previous_version_id != nil)
      status = allowed_to_edit? post.previous_version, user
    end
    status
  end

  def notify_watchers(post)
    users_to_notify = Hash.new
    post.ancestors.each do |parent|
      parent.watchers.each do |user|
        unless user == post.user
          users_to_notify[user] = parent
        end
      end
    end
    users_to_notify.each do |user, parent|
      BoardMailer.notify_watchers(post, parent, user).deliver_now
    end
  end

  private

  def clear_return_url
    session[:user_return_to] = nil
  end

  def authenticate_user_board!
    session[:user_return_to] = request.fullpath
    authenticate_user!
  end

  def add_nm(post)
    if @post.body == ""
      @post.subject += " (nm)"
    end
  end

  def post_params
    if current_user.moderator?
      params.require(:post).permit(:locked, :poofed, :override_sort_timestamp, :sort_timestamp, :body, :subject, :author, :parent_id, :watch_add, :tag_ids => [])
    else
      params.require(:post).permit(:body, :subject, :author, :parent_id, :watch_add, :tag_ids => [])
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% watch_checkbox ||= false %>
<div class="row">
  <div class="col-sm-12">
    <div class="panel-group" id="preview-accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <a class="panel-toggle" data-toggle="collapse" data-parent="#preview-accordion" href="#preview-wrapper" aria-expanded="true" aria-controls="preview-wrapper">
            Preview <b class="caret"></b>
          </a>
        </div>
        <div id="preview-wrapper" class="panel-collapse collapse in">
          <div class="panel-inner" id="preview">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% @post.body %>
<div class="row">
  <%= simple_form_for @post, wrapper: :horizontal_form, html: { class: 'form-horizontal', id: 'post-change-form' } do |f| %>
    <%= f.error_notification %>
    <% if @post.errors[:base].length > 0 %>
      <div class="alert alert-error">
        <%= f.error :base %>
      </div>
    <% end %>
    <div class="form-inputs">
      <%= f.input :parent_id, :as => :hidden %>
      <%= f.input :subject, input_html: { maxlength: 100 } %>
      <%= f.input :author, input_html: { maxlength: 80 } %>
      <% if watch_checkbox %>
        <%= f.input :watch_add, :label => "Get emails about replies to this thread", :as => :boolean,
        :wrapper => :board_vertical_boolean,
        :input_html => { checked: false },
        :disabled => @post.ancestors.joins("INNER JOIN posts_users on posts_users.post_id = posts.id")
        .where("posts_users.user_id = ?", [current_user.id]).exists? %>
      <% end %>
      <%= f.input :body, :hint => "Posts can either be written in Markdown or a subset of HTML. For formatting help, please see #{link_to 'the formatting guide', '/formatting_help', target: '_blank'}.".html_safe, :rows => 15, :cols => 50 %>

      <%= f.association :tags, :as => :check_boxes,
                        :wrapper => :tag_checkboxes,
                        :collection => Tag.where.not(
                          id: @post.ancestors.includes(:tags).map(&:tags).flatten) %>

      <% if current_user.moderator? %>
        <%= f.input :locked, :label => 'Locked thread?', wrapper: :board_vertical_boolean%>
        <%= f.input :poofed, :label => 'Poofed post?', wrapper: :board_vertical_boolean %>
        <% if !@post.persisted? %>
          <%= f.input :override_sort_timestamp, label: 'Set sort timestamp',
                      as: :boolean, :input_html => { checked: false }, wrapper: :board_vertical_boolean %>
        <% end %>
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <%= f.input :sort_timestamp %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row">
      <div class="col-sm-offset-1">
        <a href="#" onclick="event.preventDefault(); preview()" class="btn btn-success", role="button">Preview</a>
        <%= f.button :submit, class: "btn btn-primary", role: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_subforums.html.erb
<table class="table table-striped">
  <thead>
    <th>Subforum</th>
    <th>Newest thread</th>
  </thead>
  <tbody>
    <% subforums.each do |tag, posts| %>
      <% unless tag == false %>
        <tr>
          <td><%= link_to tag.name.pluralize, tagged_path(:tag_id => tag.id) %></td>
          <td><%= render :partial => 'post_subject', :object => posts[0] unless posts.empty? %></td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td><%= link_to 'None of the Above', tagged_path(:tag_id => 'nothing') %></td>
      <td><%= render :partial => 'post_subject', :object => subforums[false][0] unless subforums[false].empty?%></td>
    </tr>
  </tbody>
</table>

app/views/posts/_thread.html.erb
<%# Expects the ID of the current post, if any, to be passed in `id`.
    `bodies` causes the bodies of the posts to be displayed when true.
    Pass a hash generated by `.arrange`. `subthread` is internal-use
  only.  %>
<% def render_thread(thread, bodies, id)
     for post, subthreads in thread do %>
  <% if post.poofed && bodies && !post.next_version %>
    <div class="poof-hider">
      <a href="#thread-from-<%= post.id %>" data-turbolinks="false" style="font-weight: bold;" data-toggle="collapse" data-target="#thread-from-<%= post.id %>"
         aria-expanded="false" aria-controls="thread-from-<%= post.id %>">
        This subthread is poofed. Click to show it.
      </a>
    </div>
  <% end %>

  <% if post.poofed && bodies && !post.next_version %>
    <div id="thread-from-<%= post.id %>" class="collapse">
  <% end %>

  <% unless post.next_version %>
    <li class="post post-in-thread" id="post-<%= post.id %>">
      <span class="<%= 'current-post' if post.id == id %>">
        <%= render :partial => 'post_subject', :object => post %>
      </span>
      <% if bodies && !(post.id == id && post.root?) %>
        <% unless post.next_version %>
          <%= link_to 'Reply', new_post_path(:parent_id => post) %>
          <% if allowed_to_edit? post, current_user %>
             | <%= link_to 'Edit', edit_post_path(post) %>
          <% end %>
        <% end %>
        <div class="post-body">
          <% cache(post, namespace: "post_bodies") do %>
            <%= raw(markdown(post.body)) %>
          <% end %>
        </div>
        <span class="show-more-link"></span>
      <% elsif bodies && post.id == id && post.root? %>
        <br /><br />
      <% end %>
    </li>
    <% unless subthreads.empty? %>
    <ul class="subthread list-unstyled">
      <%= render_thread(subthreads, bodies, id) %>
    </ul>
    <% end %>

    <% if post.poofed && bodies && !post.next_version%></div> <% end %>
  <% end %>
<% end; nil %>
<% end %>
<ul class="thread row list-unstyled">
  <div class="col-sm-12">
    <%= render_thread(thread, bodies, id) %>
  </div>
</ul>

app/views/posts/index.html.erb
<% content_for(:header_title_override) { "The #{SITE_CONFIG[:title]}" } %>
<% content_for(:body_nav_tabs) do %>
  <%= render :partial => 'new_post_button'%>
  <li class="<%= 'active' if (!(cookies[:sort_mode]) || cookies[:sort_mode] == "date") %>">
    <%= link_to 'Sort by date', posts_path(:sort_mode => "date") %> </li>
  <li class="<%= 'active' if cookies[:sort_mode] == "tag" %>">
    <%= link_to 'Sort by tags', posts_path(:sort_mode => "tag") %> </li>
  <li class="<%= 'active' if cookies[:sort_mode] == "subforum" %>">
    <%= link_to 'Subforum view', posts_path(:sort_mode => "subforum") %> </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false" aria-controls="subforum-list-menu" aria-haspopup="menu">
      Jump to subforum <b class="caret"></b></a>
    <ul class="dropdown-menu" id="subforum-list-menu">
      <% Tag.all.each do |tag| %>
        <li><%= link_to tag.name.pluralize, tagged_path(:tag_id => tag.id) %></li>
      <% end %>
      <li><%= link_to "None of the Above", tagged_path(:tag_id => "nothing") %></li>
    </ul>
    </li>
    <li>
      <%= link_to 'Latest posts', latest_posts_path() %>
    </li>
<% end %>
<%= render 'header' %>

<% if cookies[:sort_mode] == "subforum" %>
  <%= render :partial => 'subforums', :object => @tagged_posts %>
<% else %>
  <% @tagged_posts.each do |tag, posts| %>
    <% unless tag == false %>
      <h3>Posts tagged: <%= tag.name %></h3>
      <% posts.each do |post| %>
        <%# Template Dependency: post/post_subject %>
        <% cache_unless(post.seeing_activity?, post, namespace: 'post_threads') do %>
        <%= render :partial => 'thread', :locals => { :bodies => false, :id => false },
                   :object =>
                   Post.arrange_nodes(post.subtree
                                       .includes([:tags])
                                       .order("ancestry NULLS FIRST, sort_timestamp DESC").load)
        %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <% if cookies[:sort_mode] == "tag" %>
    <h3>Untagged Posts</h3>
  <% end %>
  <% @tagged_posts[false].each do |post| %>
    <%# Template Dependency: post/post_subject %>
    <% cache_unless(post.seeing_activity?, post, namespace: 'post_threads') do %>
    <%= render :partial => 'thread', :locals => { :bodies => false, :id => false },
      :object =>
      Post.arrange_nodes(post.subtree
                          .includes([:tags])
                          .order("ancestry NULLS FIRST, sort_timestamp DESC").load)
    %>
    <% end %>
  <% end %>
<% end %>
<br />
<div class="row">
  <div class="col-sm-2">
    <%= render :partial => 'new_post_button', :locals => { :style => " "} %>
  </div>
</div>
<% unless cookies[:sort_mode] == "subforum" %>
  <%= will_paginate @posts %>
<% end %>

app/views/posts/latest.html.erb
<% title "Latest posts" %>
<% content_for(:header_title_override) {
   "The #{SITE_CONFIG[:title]} - Latest posts" }
%>
<% content_for(:body_nav_tabs) do %>
  <%= render :partial => 'new_post_button'%>
  <li>
    <%= link_to 'Threads', posts_path() %> </li>
  <li class="active">
    <%= link_to 'Latest posts', latest_posts_path() %></li>
  </li>
<% end %>
<%= render 'header' %>

<div class="row">
  <div class="col-sm-12">
    <p>This list is also available as a <a href="<%= url_for(action: 'latest', controller: 'posts') %>.atom">Atom/RSS feed</a></p>
  </div>
</div>
<% @posts.each do |post| %>
<% post.body %>
<%= render :partial => 'thread', :locals => { :bodies => true, :id => nil },
   :object => {post => []}
%>
<% end %>

<br />
<div class="row">
  <div class="col-sm-2">
    <%= render :partial => 'new_post_button', :locals => { :style => " "} %>
  </div>
</div>
<%= will_paginate @posts %>

app/views/posts/show.html.erb
<% title(@post.subject) %>
<%= render @post %>
<div class="btn-group">
  <% unless @post.next_version %>
    <%= link_to 'Reply', new_post_path(:parent_id => @post), :class => 'btn btn-default', :role => "button" %>
    <% if allowed_to_edit? @post, current_user %>
      <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default', :role => "button" %>
    <% end %>
    <% if user_signed_in? %>
      <% if current_user.watched_posts.exists?(@post.id) %>
        <%= link_to 'Stop reply notifications', "/posts/#{@post.id}/watch", :method => :delete, :class => "btn btn-default", :role => "button" %>
      <% else %>
        <%= link_to 'Get emails on replies', "/posts/#{@post.id}/watch", :method => :post, :class => 'btn btn-default', :role => "button" %>
      <% end %>
    <% end %>
    <% if cookies[:last_subforum] %>
      <%= link_to 'Return to messages', "/posts/tagged/#{cookies[:last_subforum]}#post-#{@post.root.id}", :class => 'btn btn-default', :role => "button" %>
    <% else %>
      <%= link_to 'Return to messages', posts_path(anchor: "post-#{@post.root.id}"), :class => 'btn btn-default', :role => "button" %>
    <% end %>
  <% end %>
  <% if user_signed_in? && current_user.moderator? %>
    <%= link_to "(CAREFUL) Delete post", post_path(@post), method: :delete,
        data: { confirm: "Are you sure you want to delete this post?" },
        class: 'btn btn-danger', role: 'button' %>
  <% end %>
</div>

<% if @post.ancestry != nil %>
  <div id="thread-position-restoration-link">
    <a href="#post-<%= @post.id %>" data-turbolinks="false">Jump to this post's position in the thread ↴</a>
  </div>
<% end %>

<div class="rest-of-thread"> <br />
<%= render :partial => 'thread', :locals => { :bodies => true, :id => @post.id },
   :object => Post.arrange_nodes(@post.root.subtree.select(:body)
                                  .includes([:tags])
                                  .order("ancestry NULLS FIRST, sort_timestamp DESC").load)
%>
</div>

app/views/posts/tagged.html.erb
<% title (@tag && @tag.name.pluralize) || "None of the Above" %>
<% content_for(:body_nav_tabs) do %>
  <%= render :partial => 'new_post_button', :locals => { :tag => @tag && @tag.id } %>
  <li><%= link_to 'All subforums', posts_path(:sort_mode => "subforum") %></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false" aria-controls="subform-list-menu" aria-haspopup="menu">
      Jump to subforum <b class="caret"></b></a>
    <ul class="dropdown-menu" id="subforum-list-menu">
      <% Tag.all.each do |tag| %>
      <li><%= link_to tag.name.pluralize, tagged_path(:tag_id => tag.id), :style => ('font-weight: bold' if tag == @tag) %></li>
      <% end %>
      <li><%= link_to "None of the Above", tagged_path(:tag_id => "nothing"), :style => ('font-weight: bold' if @tag == false) %></li>
    </ul>
  </li>
<% end %>
<%= render 'header' %>

<% @posts.each do |post| %>
  <div class="post thread" id="post-<%= post.id %>">
    <% new_post_count = post.subtree.select(&:recent?).count %>
    <% if new_post_count > 0 %>
      <span class="badge" label="<%= new_post_count %> new post".pluralize(new_post_count)
            title="<%= new_post_count %> new post".pluralize(new_post_count)><%= new_post_count %></span>
    <% end %>
    <%= render :partial => 'post_subject', :object => post %>
  </div>
<% end %>
<br />
<%= render :partial => 'new_post_button',
           :locals => { :tag => @tag && @tag.id, :style => " "} %>
<%= will_paginate @raw_posts %>