config/routes.rb
Rails.application.routes.draw do
  resources :bans

  root :to => 'posts#index'
  match 'users' => 'posts#index', :via => :delete
  get 'formatting_help' => 'pages#formatting_help'
  get 'data_collection' => 'pages#data_collection'
  devise_for :users, controllers: {
               registrations: 'users/registrations'
             }
  resources :users, :only => [:show]

  resources :posts do
    collection do
      get 'search'
      get 'latest'
      post 'preview'
      put 'preview'
      patch 'preview'
    end
  end

  match 'posts/tagged/:tag_id' => 'posts#tagged', :via => :get, :as => :tagged
  match 'posts/scrape/:year/:month' => 'posts#scrape', :via => :get, :as => :scrape
  match 'posts/:post_id/watch' => 'watches#create', :via => :post
  match 'posts/:post_id/watch' => 'watches#destroy', :via => :delete

end

app/views/layouts/_information.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <% flash ||= {} %>
      <% flash.each do |type, msg| %>
        <% if type == "notice"
             type = "success"
           end
          if type == "alert" or type == "error"
            type = "danger"
          end %>
        <% msg = [msg] unless msg.kind_of?(Array) %>
        <% msg.each do |text| %>
          <div class="alert alert-<%= type %>" role="alert"> <%=raw text %> </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) ? yield(:title) : "Index" %>
         - <%= SITE_CONFIG[:title] %></title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="<%= content_for(:title) ? yield(:title) : 'Index' %>">
  <meta property="og:site_name" content="<%= SITE_CONFIG[:title] %>">
  <meta property="og:image" content="">
  <meta property="og:type" content="website">
  <meta property="og:url" content="<%= url_for(:only_path => false, :protocol => 'https') %>" />
  <link rel="canonical" href="<%= url_for(:only_path => false, :protocol => 'https') %>" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= jquery_include_tag :google  %>
  <%= javascript_include_tag "application" %>
  <link rel="shortcut icon" href="/favicon.ico" />
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:atom, "/posts/latest.atom", {:title => "Latest posts" }) %>
  <% if current_user %>
    <style media="all" type="text/css">
      span.author-tag-for-<%= current_user.id %> {
          font-weight: bold;
      }
    </style>
  <% end %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<a class="sr-only sr-only-focusable" href="#main">Skip to main content</a>
<nav class="navbar navbar-default">
  <div class="container" id="top-nav-bar">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#nav-collapse-header-all"
              aria-expanded="false" aria-controls="nav-collapse-header-all">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= SITE_CONFIG[:title] %></a>
    </div>
    <div class="collapse navbar-collapse" id="nav-collapse-header-all">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'All posts', posts_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'New post', new_post_path %></li>
        <% end %>
      </ul>
      <%= form_tag(search_posts_path, :method => "get", :class => "navbar-form navbar-right", :role => "search") do %>
        <%= text_field_tag(:query, @query, :class => "search-query form-control col-sm-2", :placeholder => "Search ...", "aria-label" => "query") %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" aria-controls="user-menu" aria-haspopup="menu">
              Welcome, <%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu" id="user-menu">
              <li><%= link_to 'Edit your profile', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= render :partial => 'layouts/information', :locals => { :flash => flash } %>
<% flash[:info] = [] %>
<% if content_for?(:page_header) %>
  <%= yield :page_header %>
<% end %>
<div id="main" role="main">
  <%= yield %>
  <div class="row">
    <footer class="col-sm-6 col-md-offset-3">
      <p>
        This software is licensed under the
        <%= link_to "GNU Affero GPL version 3 or later", "http://www.gnu.org/licenses/agpl-3.0.html" %>.
        Source code is located <%= link_to "at Github", "https://github.com/TechnoDann/PPC-board-2.0" %>.
      </p>
      <p>
        <%= link_to 'Our data collection info', '/data_collection' %>
        &emsp;
        <%= link_to 'Current bans', bans_path %>
      </p>
    </footer>
  </div>
</div>
</body>
</html>